import { defaultTheme } from 'BlogView/pearls/theme/defaultTheme';
import { Theme } from './types';

export const themes: { key: string; name: string; theme: Theme }[] = [
  {
    key: 'default',
    name: 'Default Theme',
    theme: defaultTheme,
  },
  {
    key: 'cybernova-theme',
    name: 'CyberNova Theme',
    theme: {
      borderRadius: 10,
      textColor: '#00FF00',
      menuBackgroundColor: '#000000',
      menuHoverBackgroundColor: '#222222',
      containerBackgroundColor: '#181818',
      secondaryTextColor: '#888888',
      reader: {
        textColor: '#00FF00',
        backgroundColor: '#0A0A0A',
        codeTheme: 'dark',
        font: 'monospace',
      },
    },
  },
  {
    key: 'ocean-breeze-theme',
    name: 'Ocean Breeze Theme',
    theme: {
      borderRadius: 15,
      textColor: '#1A1A1A',
      menuBackgroundColor: '#4C9D9B',
      menuHoverBackgroundColor: '#368C88',
      containerBackgroundColor: '#FFFFFF',
      secondaryTextColor: '#6E6E6E',
      reader: {
        textColor: '#1A1A1A',
        backgroundColor: '#F0F4F4',
        codeTheme: 'light',
        font: 'serif',
      },
    },
  },
  {
    key: 'royal-velvet-theme',
    name: 'Royal Velvet Theme',
    theme: {
      borderRadius: 18,
      textColor: '#FAF0E6',
      menuBackgroundColor: '#660066',
      menuHoverBackgroundColor: '#550055',
      containerBackgroundColor: '#2A0031',
      secondaryTextColor: '#D1B7D2',
      reader: {
        textColor: '#FAF0E6',
        backgroundColor: '#1A001D',
        codeTheme: 'light',
        font: 'serif',
      },
    },
  },
  {
    key: 'tech-noir-theme',
    name: 'Tech Noir Theme',
    theme: {
      borderRadius: 12,
      textColor: '#00FFEB',
      menuBackgroundColor: '#111111',
      menuHoverBackgroundColor: '#222222',
      containerBackgroundColor: '#181818',
      secondaryTextColor: '#B0B0B0',
      reader: {
        textColor: '#00FFEB',
        backgroundColor: '#101010',
        codeTheme: 'dark',
        font: 'monospace',
      },
    },
  },
  {
    key: 'morning-sunrise-theme',
    name: 'Morning Sunrise Theme',
    theme: {
      borderRadius: 10,
      textColor: '#0D1F2D',
      menuBackgroundColor: '#FFD700',
      menuHoverBackgroundColor: '#FFB800',
      containerBackgroundColor: '#FFF5E1',
      secondaryTextColor: '#3D4C5C',
      reader: {
        textColor: '#0D1F2D',
        backgroundColor: '#FFF5E1',
        codeTheme: 'light',
        font: 'serif',
      },
    },
  },
  {
    key: 'red-alert-theme',
    name: 'Red Alert Theme',
    theme: {
      borderRadius: 8,
      textColor: '#FFFFFF',
      menuBackgroundColor: '#D32F2F',
      menuHoverBackgroundColor: '#C2185B',
      containerBackgroundColor: '#212121',
      secondaryTextColor: '#9E9E9E',
      reader: {
        textColor: '#FFFFFF',
        backgroundColor: '#B71C1C',
        codeTheme: 'dark',
        font: 'monospace',
      },
    },
  },
  {
    key: 'silver-lining-theme',
    name: 'Silver Lining Theme',
    theme: {
      borderRadius: 15,
      textColor: '#212121',
      menuBackgroundColor: '#90A4AE',
      menuHoverBackgroundColor: '#78909C',
      containerBackgroundColor: '#F5F5F5',
      secondaryTextColor: '#607D8B',
      reader: {
        textColor: '#212121',
        backgroundColor: '#F5F5F5',
        codeTheme: 'light',
        font: 'serif',
      },
    },
  },
  {
    key: 'midnight-dream-theme',
    name: 'Midnight Dream Theme',
    theme: {
      borderRadius: 14,
      textColor: '#D1C6B1',
      menuBackgroundColor: '#212121',
      menuHoverBackgroundColor: '#323232',
      containerBackgroundColor: '#121212',
      secondaryTextColor: '#A0A0A0',
      reader: {
        textColor: '#D1C6B1',
        backgroundColor: '#1C1C1C',
        codeTheme: 'dark',
        font: 'monospace',
      },
    },
  },
  {
    key: 'aurora-glow-theme',
    name: 'Aurora Glow Theme',
    theme: {
      borderRadius: 17,
      textColor: '#1A1A1A',
      menuBackgroundColor: '#FF6F61',
      menuHoverBackgroundColor: '#E84B3C',
      containerBackgroundColor: '#F2E1D2',
      secondaryTextColor: '#3B3B3B',
      reader: {
        textColor: '#1A1A1A',
        backgroundColor: '#F2E1D2',
        codeTheme: 'light',
        font: 'serif',
      },
    },
  },
  {
    key: 'stealth-mode-theme',
    name: 'Stealth Mode Theme',
    theme: {
      borderRadius: 10,
      textColor: '#FFFFFF',
      menuBackgroundColor: '#212121',
      menuHoverBackgroundColor: '#323232',
      containerBackgroundColor: '#121212',
      secondaryTextColor: '#757575',
      reader: {
        textColor: '#FFFFFF',
        backgroundColor: '#212121',
        codeTheme: 'dark',
        font: 'monospace',
      },
    },
  },
  {
    key: 'sunset-dream-theme',
    name: 'Sunset Dream Theme',
    theme: {
      borderRadius: 16,
      textColor: '#FFFFFF',
      menuBackgroundColor: '#FF4500',
      menuHoverBackgroundColor: '#D63600',
      containerBackgroundColor: '#2F2F2F',
      secondaryTextColor: '#CCCCCC',
      reader: {
        textColor: '#FFFFFF',
        backgroundColor: '#F08080',
        codeTheme: 'dark',
        font: 'serif',
      },
    },
  },
  {
    key: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    theme: {
      borderRadius: 8,
      textColor: '#00f1ff',
      menuBackgroundColor: '#1c1c1c',
      menuHoverBackgroundColor: '#00a1af',
      containerBackgroundColor: '#121212',
      secondaryTextColor: '#ff00c8',
      reader: {
        textColor: '#ff00c8',
        backgroundColor: '#1a1a1a',
        codeTheme: 'dark',
        font: 'monospace',
      },
    },
  },

  {
    key: 'tesco-theme',
    name: 'Tesco',
    theme: {
      borderRadius: 8,
      textColor: '#ffffff',
      menuBackgroundColor: '#005596',
      menuHoverBackgroundColor: '#004487',
      containerBackgroundColor: '#002243',
      secondaryTextColor: '#555555',
      reader: {
        textColor: '#333333',
        backgroundColor: '#F9F9F9',
        codeTheme: 'light',
        font: 'Arial, sans-serif',
      },
    },
  },
  {
    key: 'north-star',
    name: 'North star',
    theme: {
      borderRadius: 8,
      textColor: '#ffffff',
      menuBackgroundColor: '#000000',
      menuHoverBackgroundColor: '#111111',
      containerBackgroundColor: '#222222',
      secondaryTextColor: '#CB333B',
      reader: {
        textColor: '#333333',
        backgroundColor: '#ffffff',
        codeTheme: 'light',
        font: 'Arial, sans-serif',
      },
    },
  },
];
